name: GitHub Security Alert Export
author: Austen Stone
description: Exports GitHub code scanning, secret scanning, and dependabot security alerts to JSON
branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  enterprise:
    description: The GitHub Enterprise
    required: false
  organization:
    description: The GitHub organization
    required: false
  repository:
    description: The GitHub repository
    required: false
    default: ${{ github.repository }}
  code-scanning:
    description: Whether to export code scanning alerts
    required: false
    default: true
  code-scanning-query-parameters:
    description: "query parameters as JSON Ex: {\"state\": dismissed}"
    required: false
  secret-scanning:
    description: Whether to export secret scanning alerts
    required: false
    default: true
  secret-scanning-query-parameters:
    description: "query parameters as JSON"
    required: false
  dependabot:
    description: Whether to export dependabot alerts
    required: false
    default: true
  dependabot-query-parameters:
    description: "query parameters as JSON Ex: {\"state\": dismissed}"
    required: false
  create-artifact:
    description: Whether to create an artifact with the alerts
    required: false
    default: true

outputs:
  dependabot:
    description: Dependabot alerts as a JSON string
  code-scanning:
    description: Code scanning alerts as a JSON string
  secret-scanning:
    description: Secret scanning alerts as a JSON string

runs:
  using: "node20"
  main: "dist/index.js"
