name: GitHub Security Alert Export
author: Austen Stone
description: Exports GitHub code scanning, secret scanning, and dependabot security alerts to JSON
branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  enterprise:
    description: The GitHub Enterprise
    required: false
  organization:
    description: The GitHub organization
    required: false
  repository:
    description: The GitHub repository
    required: false
    default: ${{ github.repository }}
  code-scanning:
    description: Whether to export code scanning alerts
    required: false
    default: true
  code-scanning-query-parameters:
    description: "query parameters as JSON Ex: {\"state\": dismissed} https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#list-code-scanning-alerts-for-a-repository"
    required: false
  secret-scanning:
    description: Whether to export secret scanning alerts
    required: false
    default: true
  secret-scanning-query-parameters:
    description: "query parameters as JSON https://docs.github.com/en/rest/secret-scanning/secret-scanning?apiVersion=2022-11-28#list-secret-scanning-alerts-for-a-repository"
    required: false
  dependabot:
    description: Whether to export dependabot alerts
    required: false
    default: true
  dependabot-query-parameters:
    description: "query parameters as JSON Ex: {\"state\": dismissed} https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#list-dependabot-alerts-for-a-repository"
    required: false
  create-artifact:
    description: Whether to create an artifact with the alerts
    required: false
    default: true
  artifact-name:
    description: The name of the artifact
    required: false
    default: "GitHub Security Alerts"

outputs:
  dependabot:
    description: Dependabot alerts as a JSON string
  code-scanning:
    description: Code scanning alerts as a JSON string
  secret-scanning:
    description: Secret scanning alerts as a JSON string
  artifact-name:
    description: The name of the artifact created

runs:
  using: "node20"
  main: "dist/index.js"
