name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          github-token: ${{ secrets.PAT }}
          repository: octodemo/vulnerable-node
          create-artifact: false
      # - run: echo "$CODE_SCANNING"; echo "$SECRET_SCANNING"; echo "$DEPENDABOT"
      #   env:
      #     CODE_SCANNING: ${{ steps.export.outputs.code-scanning }}
      #     SECRET_SCANNING: ${{ steps.export.outputs.secret-scanning }}
      #     DEPENDABOT: ${{ steps.export.outputs.dependabot }}
      - uses: ./
        id: export-query-params
        with:
          github-token: ${{ secrets.PAT }}
          repository: octodemo/vulnerable-node
          code-scanning-query-parameters: '{ "severity": "critical", "state": "open" }'
          secret-scanning-query-parameters: '{ "state": "open" }'
          dependabot-query-parameters: '{ "severity": "critical", "state": "open" }'
          create-artifact: false
      - run: echo "$CODE_SCANNING"; echo "$SECRET_SCANNING"; echo "$DEPENDABOT"
        env:
          CODE_SCANNING: ${{ steps.export.outputs.code-scanning }}
          SECRET_SCANNING: ${{ steps.export.outputs.secret-scanning }}
          DEPENDABOT: ${{ steps.export.outputs.dependabot }}