name: Usage CSV
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          github-token: ${{ secrets.PAT }}
          repository: octodemo/vulnerable-node
          create-artifact: false
      - uses: austenstone/json-to-csv@main
        id: code-scanning-csv
        with:
          json-artifact-name: code-scanning
      - run: echo "${{ steps.code-scanning-csv.outputs.csv }}"