name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          github-token: ${{ secrets.PAT }}
          repository: octodemo/vulnerable-node
      - run: echo '${{ toJson(steps.export.outputs.dependabot) }}' > dependabot.json
      - uses: actions/upload-artifact@v4
        with:
          name: dependabot
          path: dependabot.json
      - run: echo '${{ toJson(steps.export.outputs.code-scanning) }}' > code-scanning.json
      - uses: actions/upload-artifact@v4
        with:
          name: code-scanning
          path: code-scanning.json
      - run: echo '${{ toJson(steps.export.outputs.secret-scanning) }}' > secret-scanning.json
      - uses: actions/upload-artifact@v4
        with:
          name: secret-scanning
          path: secret-scanning.json
