name: Usage CSV
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          github-token: ${{ secrets.PAT }}
          repository: octodemo/vulnerable-node
          create-artifact: false
      - uses: austenstone/json-to-csv@main
        id: csv
        with:
          json: ${{ steps.export.outputs.dependabot }}
      - run: echo "$CSV" > csv.csv
        env:
          CSV: ${{ steps.csv.outputs.csv }}
      - uses: actions/upload-artifact@v4
        with:
          name: csv
          path: csv.csv