name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          token: ${{ secrets.PAT }}
          enterprise: ${{ vars.enterprise }}
      - run: echo "${{ steps.export.outputs.dependabot }}" > dependabot.json
      - run: echo "${{ steps.export.outputs.code-scanning }}" > code-scanning.json
      - run: echo "${{ steps.export.outputs.secret-scanning }}" > secret-scanning.json
      