name: Usage CSV
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: octodemo/security-export
      - uses: austenstone/json-to-csv@main
        id: csv
        with:
          json-artifact-name: ${{ steps.export.outputs.artifact-name }}
          create-artifact: true
          artifact-name: "GitHub Security Alerts CSV"
      - uses: petems/csv-to-md-table-action@master
        with:
          csvinput: ${{ steps.csv.outputs.csv }}
