name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: export
        with:
          github-token: ${{ secrets.PAT }}
          repository: octodemo/vulnerable-node
      - name: Write JSON to file
        run: |
          echo '${{ steps.export.outputs.dependabot }}' | jq '.' > dependabot.json
          echo '${{ steps.export.outputs.code-scanning }}' | jq '.' > code-scanning.json
          echo '${{ steps.export.outputs.secret-scanning }}' | jq '.' > secret-scanning.json